/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RecordingId = IDL.Nat;
export const Time = IDL.Int;
export const Recording = IDL.Record({
  'id' : RecordingId,
  'tag' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'created' : Time,
  'desc' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addRecording' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [RecordingId],
      [],
    ),
  'getAllRecordings' : IDL.Func([], [IDL.Vec(Recording)], ['query']),
  'getRecording' : IDL.Func([RecordingId], [Recording], ['query']),
  'getRecordingsByTag' : IDL.Func([IDL.Text], [IDL.Vec(Recording)], ['query']),
  'removeRecording' : IDL.Func([RecordingId], [], []),
  'updateRecording' : IDL.Func(
      [RecordingId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RecordingId = IDL.Nat;
  const Time = IDL.Int;
  const Recording = IDL.Record({
    'id' : RecordingId,
    'tag' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'created' : Time,
    'desc' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addRecording' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [RecordingId],
        [],
      ),
    'getAllRecordings' : IDL.Func([], [IDL.Vec(Recording)], ['query']),
    'getRecording' : IDL.Func([RecordingId], [Recording], ['query']),
    'getRecordingsByTag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Recording)],
        ['query'],
      ),
    'removeRecording' : IDL.Func([RecordingId], [], []),
    'updateRecording' : IDL.Func(
        [RecordingId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };